[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TestSimpleCalculator_2026_FJ_GITHUB"
version = "0.0.11"
authors = [{name = "Fabrice Jumel"}]
description = "Simple calculator for packaging demo"
readme= "README.md"
license = {text = "Unlicense"}
requires-python = ">=3.10"

[project.optional-dependencies]
test = ["pytest>=7.0", "pytest-cov", "pylint", "black", "radon","build","twine"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
