name: CI/CD Python Packaging

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  install-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: pyproject.toml
    - name: Install & Lint & Test
      run: |
        make install 
        make test-smoke
        make uninstall
        make install-dev
        make lint 
        make ci

  metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Metrics
      run: |
        make install-dev
        make metrics-all

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Build
      run: |
        make install-dev
        make build
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*

  deploy-testpypi:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Publish TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ vars.TESTPYPI_TOKEN }}
      run: |
        make install-dev      
        make deploy-test

  deploy-pypi:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Publish PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        make install-dev
        make deploy
        
